version: "3"
services:
  spring-boot-app:
    build: .
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=
    networks:
      - my-network

networks:
  my-network:
