name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the stack
        uses: hoverkraft-tech/compose-action@v2.0.1
        run: docker-compose up -d
